name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # full history (not shallow)

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "boufafa.moamed@gmail.com"
          git config --global user.name "moamedBoufafa"
          git remote add hf https://huggingface.co/spaces/moamedBoufafa/license-plate-recognition.git
          git push --force https://moamedBoufafa:$HF_TOKEN@huggingface.co/spaces/moamedBoufafa/license-plate-recognition.git main
